const CAMBRIDGE_LOGIN_HOST = "https://accounts.eu1.gigya.com";
const CAMBRIDGE_LOGIN_UI_PATH = "accounts.webSdkBootstrap";
const CAMBRIDGE_LOGIN_PORT_PATH = "accounts.login"
const CAMBRIDGE_API_KEY = "4_5rnY1vVhTXaiyHmFSwS_Lw"
const CAMBRIDGE_COOKIE_GIGYA_VER_KEY = `gig_bootstrap_${CAMBRIDGE_API_KEY}`
const CAMBRIDGE_COOKIE_GIGYA_VER_VALUE = "_gigya_ver4"
const CAMBRIDGE_LOGIN_TOKEN_COOKIE_KEY = `glt_${CAMBRIDGE_API_KEY}`
const CAMBRIDGE_SDK_BUILD = "16081"
const CAMBRIDGE_DICTIONARY_HOST = "https://dictionary.cambridge.org"
const WORDLIST_WORD_PER_PAGE = 50
export {
    CAMBRIDGE_LOGIN_HOST,
    CAMBRIDGE_LOGIN_UI_PATH,
    CAMBRIDGE_LOGIN_PORT_PATH,
    CAMBRIDGE_API_KEY,
    CAMBRIDGE_SDK_BUILD,
    CAMBRIDGE_DICTIONARY_HOST,
    CAMBRIDGE_LOGIN_TOKEN_COOKIE_KEY,
    CAMBRIDGE_COOKIE_GIGYA_VER_KEY,
    CAMBRIDGE_COOKIE_GIGYA_VER_VALUE,
    WORDLIST_WORD_PER_PAGE
}